### PR TITLE
fix(radare): Fix Radare Support

### LINKED ISSUE #286: libradare support broken
Building lo2s with Radare2 (Version 5.8.2) results in the following build errors:

```bash
/home/cvonelm/lo2s/src/radare.cpp: In constructor ‘lo2s::Radare::Radare()’:
/home/cvonelm/lo2s/src/radare.cpp:30:30: error: ‘R_ASM_SYNTAX_ATT’ was not declared in this scope; did you mean ‘R_ARCH_SYNTAX_ATT’?
   30 |     r_asm_set_syntax(r_asm_, R_ASM_SYNTAX_ATT);
      |                              ^~~~~~~~~~~~~~~~
      |                              R_ARCH_SYNTAX_ATT
/home/cvonelm/lo2s/src/radare.cpp: At global scope:
/home/cvonelm/lo2s/src/radare.cpp:34:13: error: no declaration matches ‘std::string lo2s::Radare::single_instruction(char*)’
   34 | std::string Radare::single_instruction(char* buf)
      |             ^~~~~~
In file included from /home/cvonelm/lo2s/src/radare.cpp:22:
/home/cvonelm/lo2s/include/lo2s/radare.hpp:54:24: note: candidate is: ‘static std::string lo2s::Radare::single_instruction(std::byte*)’
   54 |     static std::string single_instruction(std::byte* buf);
      |                        ^~~~~~~~~~~~~~~~~~
/home/cvonelm/lo2s/include/lo2s/radare.hpp:41:7: note: ‘class lo2s::Radare’ defined here
   41 | class Radare
      |       ^~~~~~
/home/cvonelm/lo2s/src/radare.cpp: In member function ‘std::string lo2s::Radare::operator()(lo2s::Address, std::istream&)’:
/home/cvonelm/lo2s/src/radare.cpp:70:41: error: ‘struct r_asm_code_t’ has no member named ‘buf_asm’
   70 |     auto ret = single_instruction(code->buf_asm);
      |                                         ^~~~~~~
```

A quick look into the Radare source code reveals, that there were breaking changes to the API.

### PR DESCRIPTION
**Pull request by cvonelm**
There were breaking API changes in Radare.

Furthermore our homegrown Radare CMake Script did not work with newer Radare versions, so use pkg-config instead

This fixes #286

### CODE REVIEW

File: src/radare.cpp [hunk 1]
```diff
@@ -23,12 +23,20 @@
...
+
+    r_asm_use(r_asm_, R_SYS_ARCH);
+    r_anal_use(r_anal_, R_SYS_ARCH);
+
+    int sysbits = (R_SYS_BITS & R_SYS_BITS_64) ? 64 : 32;
+    r_asm_set_bits(r_asm_, sysbits);
+    r_anal_set_bits(r_anal_, sysbits);
 }
 
 std::string Radare::single_instruction(char* buf)
```
Comment (bmario) [inline src/radare.cpp:42]: The method could also have some love.
`buf` might be null. And the code is a bit inefficient.

Maybe something like this:
```c++
   if (buf == nullptr) throw ...;
   auto it = buf;
   while(*it != '\0' && *it != '\n') {
      it++;
   }
   if (it == buf) throw Error("empty instruction");
    return std::string(buf, it - 1);
```

**Review by bmario — APPROVED** [review]
