### PR TITLE
fix(warning): Fix dangling reference  to temporary warning

### LINKED ISSUE #281: Fix dangling reference to temporary warning.
Recent versions of  GCC warn about  a possible dangling reference to a temporary:

```bash
/home/cvonelm/lo2s/src/perf/event_provider.cpp: In static member function ‘static const lo2s::perf::EventDescription& lo2s::perf::EventProvider::fallback_metric_leader_event()’:
/home/cvonelm/lo2s/src/perf/event_provider.cpp:308:37: warning: possibly dangling reference to a temporary [-Wdangling-reference]
  308 |             const EventDescription& ev = get_event_by_name(candidate);
      |                                     ^~
/home/cvonelm/lo2s/src/perf/event_provider.cpp:308:59: note: the temporary was destroyed at the end of the full expression ‘lo2s::perf::EventProvider::get_event_by_name(std::__cxx11::basic_string<char>(candidate, std::allocator<char>()))’
  308 |             const EventDescription& ev = get_event_by_name(candidate);
      |                                          ~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by cvonelm**
Recent GCC versions complain about a possible dangling reference to a temporary.

Fix this warning by returning a copy of the EventDescription instead, as all code paths copy the EventDescription in the end anyways.

This fixes #281.

### CODE REVIEW

File: src/perf/event_provider.cpp [hunk 1]
```diff
@@ -305,7 +305,7 @@ const EventDescription& EventProvider::fallback_metric_leader_event()
     {
         try
         {
-            const EventDescription& ev = get_event_by_name(candidate);
+            const EventDescription ev = get_event_by_name(candidate);
```
Comment (bmario) [inline src/perf/event_provider.cpp:308]:
```suggestion
            auto ev = get_event_by_name(candidate);
```

**Review by bmario — APPROVED** [review]
