### PR TITLE
fix(metrics): Use .scale and .unit for PMU events

### LINKED ISSUE #208: .scale for metrics ignored
Test system "ariel" (Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz), **HT disabled**

Some metrics have a `.scale` file to be used for scaling (presumably only applies to PMUs)
This is not respected in the produced trace.

https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/tools/perf/util/stat-display.c#n887

```
$ perf stat -C 21 -e cpu/topdown-fetch-bubbles/ -e cpu/topdown-recovery-bubbles/ -e cpu/topdown-slots-issued/ -e cpu/topdown-slots-retired/ -e cpu/topdown-total-slots/ -- taskset -c 21 sleep 2

 Performance counter stats for 'CPU(s) 21':

         3,362,073      cpu/topdown-fetch-bubbles/
           576,768      cpu/topdown-recovery-bubbles/
         3,449,285      cpu/topdown-slots-issued/
         2,850,261      cpu/topdown-slots-retired/
        11,605,184      cpu/topdown-total-slots/

       2.004742734 seconds time elapsed
```

topdown-total-slots is expected to be larger than all other metrics, the raw value must be multiplied with 4:

```
$ cat /sys/devices/cpu/events/topdown-total-slots.scale
4
```

lo2s only reports a quarter of that (scale is not applied):

```
lo2s -E cpu/topdown-fetch-bubbles/ -E cpu/topdown-recovery-bubbles/ -E cpu/topdown-slots-issued/ -E cpu/topdown-slots-retired/ -E cpu/topdown-total-slots/ -- taskset -c 21 sleep 2
```

In the resulting trace `cpu/topdown-total-slots/` is not the largest value.

### PR DESCRIPTION
**Pull request by cvonelm**
This fixes #208

PMU events may come with a separate scaling factor, which needs to be
multiplied with the event read-out. This is located in [event_path].scale.

As I was touching the PMU event read code anyways I also added support
for parsing the [event_path].unit, which tells us the unit of the PMU event.

Traces look fine by me, can you further test this @s9105947 ?

### CODE REVIEW

File: src/perf/event_provider.cpp [hunk 1]
```diff
@@ -536,6 +537,21 @@ const EventDescription sysfs_read_event(const std::string& ev_desc)
                  << event_name << "/type=" << event.type << ",config=" << event.config
                  << ",config1=" << event.config1 << std::dec << std::noshowbase << "/";
 
+    std::ifstream scale_stream(event_path.string() + ".scale");
+
+    scale_stream >> event.scale;
```
Comment (bmario) [inline src/perf/event_provider.cpp:542]:
```suggestion

    std::ifstream scale_stream(event_path.string() + ".scale");
    scale_stream >> event.scale;
```

File: src/perf/event_provider.cpp [hunk 2]
```diff
@@ -536,6 +537,21 @@ const EventDescription sysfs_read_event(const std::string& ev_desc)
...
+    if (scale_stream.fail())
+    {
+        event.scale = 1;
+    }
+    std::ifstream unit_stream(event_path.string() + ".unit");
+
+    unit_stream >> event.unit;
```
Comment (bmario) [inline src/perf/event_provider.cpp:549]:
```suggestion
    }

    std::ifstream unit_stream(event_path.string() + ".unit");
    unit_stream >> event.unit;
```

**Review by bmario — CHANGES_REQUESTED** [review]
Don't scale values yourself. Use [value_base()](https://github.com/tud-zih-energy/otf2xx/blob/master/include/otf2xx/definition/metric_member.hpp#L145) and [value_exponent()](https://github.com/tud-zih-energy/otf2xx/blob/master/include/otf2xx/definition/metric_member.hpp#L154) instead.

**Comment by cvonelm** [comment]
value_base() is for setting whether the number is in either binary or decimal and value_exponent requires integers, while we need floating point values, as the documentation states, that `.scale` is a float 

```bash
# For power:energy-pkg on my system
cvonelm@roronoa ~/lo2s (git)-[master] % cat /sys/bus/event_source/devices/power/events/energy-pkg.scale 
2.3283064365386962890625e-10
```

**Comment by s9105947** [comment]
The scaled metric `cpu/topdown-total-slots/` reported close to zero all of the time, while the un-scaled metrics worked:

```
$ ../lo2s/build/lo2s -E cpu/topdown-fetch-bubbles/ -E cpu/topdown-recovery-bubbles/ -E cpu/topdown-slots-issued/ -E cpu/topdown-slots-retired/ -E cpu/topdown-total-slots/ -- taskset -c 21 ./a.out
[ lo2s: Child exited. Stopping measurements and closing trace. ]
[ lo2s: taskset -c 21 /home/s9105947/2022-06-07-lo2s-tma-tinkering/workload/a.out  (0), 1 threads, 4.71865s CPU, 4.10435s total ]
[ lo2s: 6 wakeups, wrote 31.36 KiB lo2s_trace_2022-06-14T10-48-43 ]
```

vampir_no_scaled

Perhaps the scale is not parsed correctly?
```
$ cat /sys/devices/cpu/events/topdown-total-slots.scale
4
```

```
$ otf2-print lo2s_trace_2022-06-14T10-48-43/traces.otf2 | grep 'cpu/topdown-total-slots/'
METRIC                                         1      606440489291318  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 2.00551e+08), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 9.86937e+08), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 7.79398e+07), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 1.62059e+09), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 3.95001e+09), ("cpu/topdown-total-slots/" <6>; DOUBLE; 2.36912e-314), ("time
_enabled" <7>; UINT64; 200447904), ("time_running" <8>; UINT64; 99955091)
METRIC                                         1      606440689266205  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 4.00583e+08), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 1.96538e+09), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 1.57317e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 3.27052e+09), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 7.96154e+09), ("cpu/topdown-total-slots/" <6>; DOUBLE; 4.73272e-314), ("time
_enabled" <7>; UINT64; 400422215), ("time_running" <8>; UINT64; 199929478)
METRIC                                         1      606440889241103  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 6.00614e+08), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 2.94622e+09), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 2.36529e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 4.9203e+09), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 1.19746e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 7.09632e-314), ("time_
enabled" <7>; UINT64; 600397092), ("time_running" <8>; UINT64; 299904327)
METRIC                                         1      606441089215151  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 8.00644e+08), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 3.92221e+09), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 3.15937e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 6.57075e+09), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 1.59865e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 9.45992e-314), ("time
_enabled" <7>; UINT64; 800371123), ("time_running" <8>; UINT64; 399879078)
METRIC                                         1      606441289190520  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 1.00068e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 4.89557e+09), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 3.95354e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 8.22212e+09), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 1.9999e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 1.18235e-313), ("time_
enabled" <7>; UINT64; 1000346494), ("time_running" <8>; UINT64; 499854165)
METRIC                                         1      606441489165952  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 1.20071e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 5.87136e+09), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 4.74782e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 9.87269e+09), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 2.40108e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 1.41871e-313), ("time
_enabled" <7>; UINT64; 1200321900), ("time_running" <8>; UINT64; 599829153)
METRIC                                         1      606441689140342  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 1.40074e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 6.84623e+09), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 5.54283e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 1.15237e+10), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 2.80234e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 1.65507e-313), ("time
_enabled" <7>; UINT64; 1400296282), ("time_running" <8>; UINT64; 699804191)
METRIC                                         1      606441889115202  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 1.60077e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 7.82125e+09), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 6.33528e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 1.31747e+10), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 3.20367e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 1.89144e-313), ("time
_enabled" <7>; UINT64; 1600271128), ("time_running" <8>; UINT64; 799779123)
METRIC                                         1      606442089097117  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 1.8008e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 8.79862e+09), ("cpu/topdown-recovery-b
ubbles/" <3>; DOUBLE; 7.12822e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 1.48248e+10), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 3.60492e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 2.12779e-313), ("time_
enabled" <7>; UINT64; 1800246221), ("time_running" <8>; UINT64; 899753773)
METRIC                                         1      606442289071388  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 2.00083e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 9.77608e+09), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 7.92171e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 1.64752e+10), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 4.00618e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 2.36415e-313), ("time
_enabled" <7>; UINT64; 2000220468), ("time_running" <8>; UINT64; 999728371)
METRIC                                         1      606442489045841  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 2.20086e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 1.07549e+10), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 8.71521e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 1.81251e+10), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 4.40734e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 2.60051e-313), ("time
_enabled" <7>; UINT64; 2200194917), ("time_running" <8>; UINT64; 1099703141)
METRIC                                         1      606442689020484  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 2.40089e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 1.1738e+10), ("cpu/topdown-recovery-b
ubbles/" <3>; DOUBLE; 9.5074e+08), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 1.97744e+10), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 4.80864e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 2.83687e-313), ("time_e
nabled" <7>; UINT64; 2400169541), ("time_running" <8>; UINT64; 1199677808)
METRIC                                         1      606442888994423  Metric: 3, 8 Values: ("cpu-clock" <1>; DOUBLE; 2.60092e+09), ("cpu/topdown-fetch-bubbles/" <2>; DOUBLE; 1.27154e+10), ("cpu/topdown-recovery-
bubbles/" <3>; DOUBLE; 1.03011e+09), ("cpu/topdown-slots-issued/" <4>; DOUBLE; 2.14246e+10), ("cpu/topdown-slots-retired/" <5>; DOUBLE; 5.20981e+10), ("cpu/topdown-total-slots/" <6>; DOUBLE; 3.07323e-313), ("time
_enabled" <7>; UINT64; 2600143474), ("time_running" <8>; UINT64; 1299652644)
[...]
```

the corresponding `perf stat` call still reports the non-zero total for `cpu/topdown-total-slots/`:

```
$ perf stat -e cpu/topdown-fetch-bubbles/ -e cpu/topdown-recovery-bubbles/ -e cpu/topdown-slots-issued/ -e cpu/topdown-slots-retired/ -e cpu/topdown-total-slots/ -- taskset -c 21 ./a.out

 Performance counter stats for 'taskset -c 21 /home/s9105947/2022-06-07-lo2s-tma-tinkering/workload/a.out':

     4,896,080,062      cpu/topdown-fetch-bubbles/
     6,384,329,524      cpu/topdown-recovery-bubbles/
    33,221,038,223      cpu/topdown-slots-issued/
    20,182,866,690      cpu/topdown-slots-retired/
    48,136,262,468      cpu/topdown-total-slots/

       4.024470153 seconds time elapsed

       4.013735000 seconds user
       0.007995000 seconds sys
```

**Comment by bmario** [comment]
> value_base() is for setting whether the number is in either binary or decimal and value_exponent requires integers, while we need floating point values, as the documentation states, that `.scale` is a float

Well, with the magic of log you can get:

`2.3283064365386962890625e-10 == 1e(log(2.3283064365386962890625e-10))`

**Review by bmario — CHANGES_REQUESTED** [review]

File: src/perf/event_provider.cpp [hunk 3]
```diff
@@ -536,6 +537,21 @@ const EventDescription sysfs_read_event(const std::string& ev_desc)
                  << event_name << "/type=" << event.type << ",config=" << event.config
                  << ",config1=" << event.config1 << std::dec << std::noshowbase << "/";
 
+    std::ifstream scale_stream(event_path.string() + ".scale");
+
+    scale_stream >> event.scale;
+    if (scale_stream.fail())
+    {
+        event.scale = 1;
+    }
```
[the remark this answers is not in the document]
Comment (cvonelm) [reply src/perf/event_provider.cpp:546]: If i read the ifstream Documentation correctly, `operator>>` does not guarantee that the variable we are writing to is untouched in the event of an error.
